export const ShopRoute = '/shop';
export const HomeRoute = '/';
export const RegisterRoute ='/registration';
export const AuthRoute ='/authentication';
export const AboutRoute = '/about_us';
export const BooksRoute = '/books';
export const NewsRoute = '/news';
export const ContactsRoute = '/contacts';
export const LOCAL_API_URL = "http://localhost:5000/api"
